"""empty message

Revision ID: 1dd5d8b47253
Revises: 
Create Date: 2020-09-18 18:35:40.012911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd5d8b47253'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kelas', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kelas')
    )
    op.create_table('pembayaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('bulan', sa.Integer(), nullable=False),
    sa.Column('nis_siswa', sa.String(length=32), nullable=False),
    sa.Column('nama_siswa', sa.String(length=32), nullable=False),
    sa.Column('jenis_siswa', sa.Integer(), nullable=False),
    sa.Column('tgl_pembayaran', sa.Date(), nullable=False),
    sa.Column('nominal', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('sekolah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_sekolah', sa.String(length=32), nullable=False),
    sa.Column('alamat_sekolah', sa.String(length=32), nullable=False),
    sa.Column('kepala_sekolah', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tahun_ajaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tahun_ajaran')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=95), nullable=False),
    sa.Column('nama', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nis_siswa', sa.String(length=32), nullable=False),
    sa.Column('nama_siswa', sa.String(length=32), nullable=False),
    sa.Column('jenis_kelamin', sa.Integer(), nullable=False),
    sa.Column('alamat_siswa', sa.String(length=128), nullable=False),
    sa.Column('agama', sa.String(length=32), nullable=False),
    sa.Column('jenis_siswa', sa.Integer(), nullable=False),
    sa.Column('id_tahun_ajaran', sa.Integer(), nullable=False),
    sa.Column('id_kelas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_kelas'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['id_tahun_ajaran'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nis_siswa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siswa')
    op.drop_table('user')
    op.drop_table('tahun_ajaran')
    op.drop_table('sekolah')
    op.drop_table('pembayaran')
    op.drop_table('kelas')
    # ### end Alembic commands ###
